In [23]:
""" Student Marks Analysis System

Scenario:
A school wants to analyze marks of 5 students in 4 subjects. They want to:
1. Store the marks in a 2D array.
2. Calculate total marks and percentage for each student.
3. Find highest and lowest marks in each subject.
4. Reshape and flatten arrays for further analysis.

We’ll solve this using NumPy.
"""

' Student Marks Analysis System\n\nScenario:\nA school wants to analyze marks of 5 students in 4 subjects. They want to:\n1. Store the marks in a 2D array.\n2. Calculate total marks and percentage for each student.\n3. Find highest and lowest marks in each subject.\n4. Reshape and flatten arrays for further analysis.\n\nWe’ll solve this using NumPy.\n'

In [8]:
import numpy as np

# 1: Input marks for 5 students in 4 subjects
marks = np.array([
    [85, 92, 78, 90],  # Student 1
    [76, 85, 83, 88],  # Student 2
    [91, 89, 95, 94],  # Student 3
    [68, 74, 80, 72],  # Student 4
    [88, 90, 85, 87]   # Student 5
])

print("Marks Array:\n", marks)

Marks Array:
 [[85 92 78 90]
 [76 85 83 88]
 [91 89 95 94]
 [68 74 80 72]
 [88 90 85 87]]


In [27]:
# 2: Calculate total and percentage
total_marks = marks.sum(axis=1)  # sum across columns for each student
percentage = total_marks / 4     # 4 subjects

print("\nTotal Marks of each student:", total_marks)
print("Percentage of each student:", percentage)



Total Marks of each student: [345 332 369 294 350]
Percentage of each student: [86.25 83.   92.25 73.5  87.5 ]


In [29]:
# 3: Find highest and lowest marks in each subject
highest_per_subject = marks.max(axis=0)
lowest_per_subject = marks.min(axis=0)

print("\nHighest marks in each subject:", highest_per_subject)
print("Lowest marks in each subject:", lowest_per_subject)




Highest marks in each subject: [91 92 95 94]
Lowest marks in each subject: [68 74 78 72]


In [31]:
# 4: Reshape marks array (flatten it for analytics)
flattened_marks = marks.flatten()
reshaped_marks = marks.reshape(4, 5)  # reshape for demonstration

print("\nFlattened marks:", flattened_marks)
print("Reshaped marks (4x5):\n", reshaped_marks)



Flattened marks: [85 92 78 90 76 85 83 88 91 89 95 94 68 74 80 72 88 90 85 87]
Reshaped marks (4x5):
 [[85 92 78 90 76]
 [85 83 88 91 89]
 [95 94 68 74 80]
 [72 88 90 85 87]]


In [33]:
# 5: Slicing example: marks of first 3 students in first 2 subjects
slice_marks = marks[:3, :2]
print("\nMarks of first 3 students in first 2 subjects:\n", slice_marks)


Marks of first 3 students in first 2 subjects:
 [[85 92]
 [76 85]
 [91 89]]


In [23]:
import numpy as np

# 1: Input marks for 5 students in 4 subjects
marks = np.array([
    [85, 92, 78, 90],  
    [76, 85, 83, 88],  
    [91, 89, 95, 94],  
    [68, 74, 80, 72],  
    [88, 90, 85, 87]   
])

print("Marks Array:\n", marks)

# 2: Calculate total and percentage
total_marks = marks.sum(axis=1)  # sum across columns for each student
percentage = total_marks / 4     # 4 subjects

print("\nTotal Marks of each student:", total_marks)
print("Percentage of each student:", percentage)

# 3: Find highest and lowest marks in each subject
highest_per_subject = marks.max(axis=0)
lowest_per_subject = marks.min(axis=0)

print("\nHighest marks in each subject:", highest_per_subject)
print("Lowest marks in each subject:", lowest_per_subject)

# 4: Reshape marks array (flatten it for analytics)
flattened_marks = marks.flatten()
reshaped_marks = marks.reshape(4, 5)  # reshape for demonstration

print("\nFlattened marks:", flattened_marks)
print("Reshaped marks (4x5):\n", reshaped_marks)

# 5: Slicing example: marks of first 3 students in first 2 subjects
slice_marks = marks[:3, :2]
print("\nMarks of first 3 students in first 2 subjects:\n", slice_marks)


Marks Array:
 [[85 92 78 90]
 [76 85 83 88]
 [91 89 95 94]
 [68 74 80 72]
 [88 90 85 87]]

Total Marks of each student: [345 332 369 294 350]
Percentage of each student: [86.25 83.   92.25 73.5  87.5 ]

Highest marks in each subject: [91 92 95 94]
Lowest marks in each subject: [68 74 78 72]

Flattened marks: [85 92 78 90 76 85 83 88 91 89 95 94 68 74 80 72 88 90 85 87]
Reshaped marks (4x5):
 [[85 92 78 90 76]
 [85 83 88 91 89]
 [95 94 68 74 80]
 [72 88 90 85 87]]

Marks of first 3 students in first 2 subjects:
 [[85 92]
 [76 85]
 [91 89]]
