In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [61]:
import numpy as np

In [20]:
print(np.__version__)

1.26.4


In [22]:
## 1. Creating Arrays

In [24]:
## 1D Array

In [26]:
list1 =[1,2,3]
print(list1)

[1, 2, 3]


In [28]:
arr_list1 = np.array(list1)
print(arr_list1)

[1 2 3]


In [30]:
print(type(arr_list1))

<class 'numpy.ndarray'>


In [33]:
## 2D Array

In [35]:
list1 =[1,2,3]
list2 =[2,4,6]
arr_list1_2=np.array([list1,list2])
print(arr_list1_2)

[[1 2 3]
 [2 4 6]]


In [37]:
print(arr_list1_2.ndim)     ## .ndim for no. of dimantion

2


In [40]:
list1 =[1,2,3]
list2 =[2,4,6]
list3 =[3,5,7]
arr_list1_3 =np.array([[list1,list2,list3]])
print(arr_list1_3)

[[[1 2 3]
  [2 4 6]
  [3 5 7]]]


In [42]:
print(arr_list1_3.ndim)

3


In [45]:
# 2.numpy array attributes

In [71]:
 arr1 = np.array ([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [73]:
print("Shape",arr1.shape)
print("size",arr1.size)
print("dTypes",arr1.dtype)
print("n_dim",arr1.ndim)

Shape (2, 3)
size 6
dTypes int32
n_dim 2


In [55]:
#Homwork :
##create 2 array- 1d and 3D, and find its attributes

import numpy as np

# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# 3D array
arr_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

# Attributes of 1D array
print("1D Array:", arr_1d)
print("ndim:", arr_1d.ndim)
print("shape:", arr_1d.shape)
print("size:", arr_1d.size)
print("dtype:", arr_1d.dtype)

print("\n-------------------\n")

# Attributes of 3D array
print("3D Array:", arr_3d)
print("ndim:", arr_3d.ndim)
print("shape:", arr_3d.shape)
print("size:", arr_3d.size)
print("dtype:", arr_3d.dtype)


1D Array: [1 2 3 4 5]
ndim: 1
shape: (5,)
size: 5
dtype: int32

-------------------

3D Array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
ndim: 3
shape: (2, 2, 2)
size: 8
dtype: int32


In [ ]:
#3. Array initialization Metods

In [75]:
# #Zero Array

zero_arr =np.zero((2,3))
print(zero_arr)

AttributeError: module 'numpy' has no attribute 'zero'