In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [1]:
import numpy as np

In [20]:
print(np.__version__)

1.26.4


In [22]:
## 1. Creating Arrays

In [24]:
## 1D Array

In [26]:
list1 =[1,2,3]
print(list1)

[1, 2, 3]


In [28]:
arr_list1 = np.array(list1)
print(arr_list1)

[1 2 3]


In [30]:
print(type(arr_list1))

<class 'numpy.ndarray'>


In [3]:
import numpy as np

# Array creation
arr1 = np.array([1, 2, 3, 4])
arr2 = np.arange(5, 10)           
arr3 = np.zeros((2, 3))           
arr4 = np.ones((3, 2))            # 3x2 array of ones
arr5 = np.random.randint(1, 20, (2, 4))  # random integers between 1 and 20

print("arr1:", arr1)
print("Shape of arr5:", arr5.shape)
print("Data type of arr5:", arr5.dtype)
print("Number of dimensions:", arr5.ndim)


arr1: [1 2 3 4]
Shape of arr5: (2, 4)
Data type of arr5: int32
Number of dimensions: 2


In [33]:
## 2D Array

In [35]:
list1 =[1,2,3]
list2 =[2,4,6]
arr_list1_2=np.array([list1,list2])
print(arr_list1_2)

[[1 2 3]
 [2 4 6]]


In [37]:
print(arr_list1_2.ndim)     ## .ndim for no. of dimantion

2


In [40]:
list1 =[1,2,3]
list2 =[2,4,6]
list3 =[3,5,7]
arr_list1_3 =np.array([[list1,list2,list3]])
print(arr_list1_3)

[[[1 2 3]
  [2 4 6]
  [3 5 7]]]


In [42]:
print(arr_list1_3.ndim)

3


In [45]:
# 2.numpy array attributes

In [28]:
arr1 = np.array ([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [15]:
print("Shape",arr1.shape)
print("size",arr1.size)
print("dTypes",arr1.dtype)
print("n_dim",arr1.ndim)

Shape (5,)
size 5
dTypes int64
n_dim 1


In [13]:

##create 2 array- 1d and 3D, and find its attributes

import numpy as np

# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# 3D array
arr_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

# Attributes of 1D array
print("1D Array:", arr_1d)
print("ndim:", arr_1d.ndim)
print("shape:", arr_1d.shape)
print("size:", arr_1d.size)
print("dtype:", arr_1d.dtype)

print("\n-------------------\n")

# Attributes of 3D array
print("3D Array:", arr_3d)
print("ndim:", arr_3d.ndim)
print("shape:", arr_3d.shape)
print("size:", arr_3d.size)
print("dtype:", arr_3d.dtype)


1D Array: [1 2 3 4 5]
ndim: 1
shape: (5,)
size: 5
dtype: int64

-------------------

3D Array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
ndim: 3
shape: (2, 2, 2)
size: 8
dtype: int64


In [16]:
#3. Array initialization Metods

In [9]:
arr1 = np.array ([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [11]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
print("1D Array:", arr1)

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

1D Array: [10 20 30 40 50]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [13]:
# zeros
arr_zeros = np.zeros((2, 3))
print("Zeros array:\n", arr_zeros)

# ones
arr_ones = np.ones((3, 2))
print("Ones array:\n", arr_ones)

# full
arr_full = np.full((2, 2), 7)
print("Full array with 7:\n", arr_full)

# arange
arr_arange = np.arange(0, 10, 2)
print("Arange array:", arr_arange)

# linspace
arr_linspace = np.linspace(0, 1, 5)
print("Linspace array:", arr_linspace)

# random
arr_random = np.random.rand(2, 2)
print("Random array:\n", arr_random)


Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Full array with 7:
 [[7 7]
 [7 7]]
Arange array: [0 2 4 6 8]
Linspace array: [0.   0.25 0.5  0.75 1.  ]
Random array:
 [[0.04658018 0.49981259]
 [0.89644557 0.13479321]]


In [9]:
# 4 Indexing , Slicing , Reshaping , Flatten

In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Indexing
print("Element at [1,2]:", arr[1, 2])  

# Slicing
print("First row:", arr[0, :])
print("Second column:", arr[:, 1])

# Reshaping
reshaped = arr.reshape(1, 9)
print("Reshaped array:", reshaped)

# Flatten
flattened = arr.flatten()
print("Flattened array:", flattened)


Element at [1,2]: 6
First row: [1 2 3]
Second column: [2 5 8]
Reshaped array: [[1 2 3 4 5 6 7 8 9]]
Flattened array: [1 2 3 4 5 6 7 8 9]


In [22]:

#indexing

import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print("Original Array:\n", arr)

# Access a single element
print("Element at row 1, column 2:", arr[1, 2])  

# Access an entire row
print("Second row:", arr[1, :])  

# Access an entire column
print("Third column:", arr[:, 2])  


Original Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Element at row 1, column 2: 60
Second row: [40 50 60]
Third column: [30 60 90]
